name: event_runner
description: Event Runner to create and manage events
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_sticky_header: ^0.6.1
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
